server:
  port: 9099
  servlet:
    context-path: "/"

spring:
  application:
    name: ruiliFota

  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.111.9.209:3306/fota?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: AppHikariCP
      minimum-idle: 5
      maximum-pool-size: 25
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 10000
      auto-commit: true
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  data:
    mongodb:
      uri: mongodb://47.111.9.209:27017/fota_firmware
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis:
  configuration:
    cache-enabled: false
  type-aliases-package: com.ruili.fota.meta.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.ruili.fota.common.BaseMapper
  not-empty: false
  identity: MYSQL

logging:
  level:
    com.ruili.fota: debug

netty:
  port: 9090
  keepalive: true #Socket参数，连接保活，默认值为False。启用该功能时，TCP会主动探测空闲连接的有效性。可以将此功能视为TCP的心跳机制，需要注意的是：默认的心跳间隔是7200s即2小时。Netty默认关闭该功能
  backlog: 2048 #  Socket参数，服务端接受连接的队列长度，如果队列已满，客户端连接将被拒绝
  nodelay: true #TCP参数，立即发送数据，默认值为Ture（Netty默认为True而操作系统默认为False）。该值设置Nagle算法的启用，改算法将小的碎片数据连接成更大的报文来最小化所发送的报文的数量，如果需要发送一些较小的报文，则需要禁用该算法。Netty默认禁用该算法，从而最小化报文传输延时。
  reuseaddr: true #地址复用，